# Generated by Django 2.0.6 on 2019-05-24 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCategory',
            fields=[
                ('category_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('book_counts', models.IntegerField(blank=True, null=True)),
                ('category_pid', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'd_category',
            },
        ),
        migrations.CreateModel(
            name='DOrderiterm',
            fields=[
                ('shop_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shop_num', models.BigIntegerField()),
                ('total_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'd_orderiterm',
            },
        ),
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('detail_address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('telphone', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_mobile', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('book_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=128)),
                ('book_author', models.CharField(max_length=64)),
                ('book_publish', models.CharField(max_length=128)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('revision', models.IntegerField(blank=True, null=True)),
                ('book_isbn', models.CharField(blank=True, max_length=64, null=True)),
                ('word_count', models.CharField(blank=True, max_length=64, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('open_type', models.CharField(blank=True, max_length=20, null=True)),
                ('book_paper', models.CharField(blank=True, max_length=64, null=True)),
                ('book_wrapper', models.CharField(blank=True, max_length=64, null=True)),
                ('book_price', models.FloatField(blank=True, null=True)),
                ('book_dprice', models.FloatField(blank=True, null=True)),
                ('editor_recommendation', models.TextField(blank=True, null=True)),
                ('content_introduction', models.TextField(blank=True, null=True)),
                ('author_introduction', models.TextField(blank=True, null=True)),
                ('menu', models.TextField(blank=True, null=True)),
                ('media_review', models.TextField(blank=True, null=True)),
                ('digest_image_path', models.TextField(blank=True, null=True)),
                ('product_image_path', models.TextField(blank=True, null=True)),
                ('series_name', models.CharField(blank=True, max_length=128, null=True)),
                ('printing_time', models.DateTimeField(blank=True, null=True)),
                ('impression', models.CharField(blank=True, max_length=64, null=True)),
                ('stock', models.BigIntegerField(blank=True, null=True)),
                ('shelve_datetime', models.DateTimeField(blank=True, null=True)),
                ('customer_socre', models.FloatField(blank=True, null=True)),
                ('book_status', models.IntegerField(blank=True, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
                ('book_category', models.ForeignKey(blank=True, db_column='book_category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dangapp.DCategory')),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='TConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
                ('code_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_confirm_string',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num', models.BigIntegerField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('order_addrid', models.ForeignKey(db_column='order_addrid', on_delete=django.db.models.deletion.DO_NOTHING, to='dangapp.TAddress')),
            ],
            options={
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.TextField()),
                ('user_name', models.CharField(max_length=30)),
                ('user_status', models.IntegerField(default=0)),
                ('c_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.AddField(
            model_name='torder',
            name='order_uid',
            field=models.ForeignKey(db_column='order_uid', on_delete=django.db.models.deletion.DO_NOTHING, to='dangapp.TUser'),
        ),
        migrations.AddField(
            model_name='tconfirmstring',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to='dangapp.TUser'),
        ),
        migrations.AddField(
            model_name='taddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dangapp.TUser'),
        ),
        migrations.AddField(
            model_name='dorderiterm',
            name='shop_bookid',
            field=models.ForeignKey(db_column='shop_bookid', on_delete=django.db.models.deletion.DO_NOTHING, to='dangapp.TBook'),
        ),
        migrations.AddField(
            model_name='dorderiterm',
            name='shop_ordid',
            field=models.ForeignKey(db_column='shop_ordid', on_delete=django.db.models.deletion.DO_NOTHING, to='dangapp.TOrder'),
        ),
    ]
